# Generated by Django 6.0.1 on 2026-01-21 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScannedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(upload_to="scanned_documents/%Y/%m/%d/")),
                (
                    "upload_method",
                    models.CharField(
                        choices=[
                            ("camera", "Camera Capture"),
                            ("upload", "File Upload"),
                        ],
                        default="upload",
                        max_length=10,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("file_size", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
