# Generated by Django 6.0.1 on 2026-01-27 09:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letara", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HandwritingGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter_form",
                    models.FloatField(
                        help_text="Quality of letter formation",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "size",
                    models.FloatField(
                        help_text="Letter size in relation to template character size",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "line_align",
                    models.FloatField(
                        help_text="Alignment with baseline and proper spacing",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "orientation",
                    models.FloatField(
                        help_text="Proper slant and angle of letters",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        blank=True,
                        help_text="Overall handwriting score",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("graded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Detailed feedback for the student"
                    ),
                ),
                (
                    "strengths",
                    models.TextField(
                        blank=True, help_text="What the student does well"
                    ),
                ),
                (
                    "areas_for_improvement",
                    models.TextField(blank=True, help_text="Areas that need work"),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hw_grade",
                        to="letara.scanneddocument",
                    ),
                ),
            ],
        ),
    ]
