# Generated by Django 6.0.1 on 2026-01-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letara", "0002_handwritinggrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="is_graded",
            field=models.BooleanField(default=False),
        ),
    ]
